"""add_speciality_table

Revision ID: 19edfa308001
Revises: 5058ff36bd61
Create Date: 2026-01-13 15:50:03.690535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19edfa308001'
down_revision: Union[str, Sequence[str], None] = '5058ff36bd61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('education_type', sa.Enum('BACHELOR', 'MASTER', name='educationtype'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialities_id'), 'specialities', ['id'], unique=False)
    op.create_index(op.f('ix_specialities_name'), 'specialities', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specialities_name'), table_name='specialities')
    op.drop_index(op.f('ix_specialities_id'), table_name='specialities')
    op.drop_table('specialities')
    # ### end Alembic commands ###
