"""Change_semester_to_array

Revision ID: 2ba71d731f18
Revises: bd749cc7a623
Create Date: 2026-01-13 18:05:22.849331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ba71d731f18'
down_revision: Union[str, Sequence[str], None] = 'bd749cc7a623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Added server_default='{}' to prevent NotNullViolationError on existing rows
    op.add_column('curriculums', sa.Column('semesters', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'))
    op.drop_column('curriculums', 'semester')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculums', sa.Column('semester', postgresql.ENUM('KUZGI', 'BAHORGI', name='semestertype'), server_default=sa.text("'KUZGI'::semestertype"), autoincrement=False, nullable=False))
    op.drop_column('curriculums', 'semesters')
    # ### end Alembic commands ###
