"""Add_name_to_workload

Revision ID: 41af8eb2afb2
Revises: 76996dcd6484
Create Date: 2026-01-13 18:38:03.889701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41af8eb2afb2'
down_revision: Union[str, Sequence[str], None] = '76996dcd6484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workloads', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workloads', 'name')
    # ### end Alembic commands ###
