"""add_edu_plan_model

Revision ID: 4cc0c1bf1b08
Revises: 6c818e6aaa47
Create Date: 2026-01-14 08:57:00.924098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc0c1bf1b08'
down_revision: Union[str, Sequence[str], None] = '6c818e6aaa47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edu_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('speciality_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edu_plans_id'), 'edu_plans', ['id'], unique=False)
    op.create_index(op.f('ix_edu_plans_name'), 'edu_plans', ['name'], unique=False)
    op.drop_index(op.f('ix_curriculums_id'), table_name='subjects')
    op.drop_index(op.f('ix_curriculums_name'), table_name='subjects')
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=False)
    op.add_column('workloads', sa.Column('edu_plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workloads', 'edu_plans', ['edu_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workloads', type_='foreignkey')
    op.drop_column('workloads', 'edu_plan_id')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.create_index(op.f('ix_curriculums_name'), 'subjects', ['name'], unique=False)
    op.create_index(op.f('ix_curriculums_id'), 'subjects', ['id'], unique=False)
    op.drop_index(op.f('ix_edu_plans_name'), table_name='edu_plans')
    op.drop_index(op.f('ix_edu_plans_id'), table_name='edu_plans')
    op.drop_table('edu_plans')
    # ### end Alembic commands ###
