"""Remove_teacher_id_from_workloads

Revision ID: 76996dcd6484
Revises: 779d1ab52dfe
Create Date: 2026-01-13 18:28:17.497640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76996dcd6484'
down_revision: Union[str, Sequence[str], None] = '779d1ab52dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workloads_teacher_id_fkey'), 'workloads', type_='foreignkey')
    op.drop_column('workloads', 'teacher_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workloads', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('workloads_teacher_id_fkey'), 'workloads', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
