"""Add_he_lab_split_to_groups

Revision ID: 779d1ab52dfe
Revises: 2ba71d731f18
Create Date: 2026-01-13 18:21:20.915863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779d1ab52dfe'
down_revision: Union[str, Sequence[str], None] = '2ba71d731f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('he_lab_split', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'he_lab_split')
    # ### end Alembic commands ###
