"""change_speciality_enum_to_string

Revision ID: aacb29f34754
Revises: f59a51bc0bbc
Create Date: 2026-01-20 12:26:49.403250

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aacb29f34754"
down_revision: Union[str, Sequence[str], None] = "f59a51bc0bbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "specialities",
        "education_type",
        existing_type=postgresql.ENUM("BACHELOR", "MASTER", name="educationtype"),
        type_=sa.String(),
        existing_nullable=False,
        postgresql_using="education_type::text",
    )

    # Data migration: Update any existing 'BACHELOR'/'MASTER' to 'Bakalavr'/'Magistr'
    op.execute(
        "UPDATE specialities SET education_type = 'Bakalavr' WHERE education_type = 'BACHELOR'"
    )
    op.execute(
        "UPDATE specialities SET education_type = 'Magistr' WHERE education_type = 'MASTER'"
    )

    # Drop the old enum type
    op.execute("DROP TYPE educationtype")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "specialities",
        "education_type",
        existing_type=sa.String(),
        type_=postgresql.ENUM("BACHELOR", "MASTER", name="educationtype"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
