"""Add_curriculum_fields_and_optional_teacher

Revision ID: bd749cc7a623
Revises: e5a956f2ff19
Create Date: 2026-01-13 18:01:56.015754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd749cc7a623'
down_revision: Union[str, Sequence[str], None] = 'e5a956f2ff19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculums', sa.Column('credits', sa.Integer(), nullable=False, server_default='0'))
    
    # Create enum manually
    semester_type = sa.Enum('KUZGI', 'BAHORGI', name='semestertype')
    semester_type.create(op.get_bind())
    
    op.add_column('curriculums', sa.Column('semester', semester_type, nullable=False, server_default='KUZGI'))
    
    op.alter_column('workloads', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workloads', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('curriculums', 'semester')
    
    # Drop enum manually
    semester_type = sa.Enum('KUZGI', 'BAHORGI', name='semestertype')
    semester_type.drop(op.get_bind())
    
    op.drop_column('curriculums', 'credits')
    # ### end Alembic commands ###
