"""add_user_fields

Revision ID: ddf93bef6c49
Revises: ca2982e3681c
Create Date: 2026-01-13 08:56:13.984668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf93bef6c49'
down_revision: Union[str, Sequence[str], None] = 'ca2982e3681c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passport_series', sa.String(), nullable=True))
    op.add_column('users', sa.Column('jshshir', sa.String(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_jshshir'), 'users', ['jshshir'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_jshshir'), table_name='users')
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'username')
    op.drop_column('users', 'jshshir')
    op.drop_column('users', 'passport_series')
    # ### end Alembic commands ###
