"""change_enums_to_string

Revision ID: e43bc532666b
Revises: aacb29f34754
Create Date: 2026-01-20 13:21:25.401404

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e43bc532666b"
down_revision: Union[str, Sequence[str], None] = "aacb29f34754"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Groups: Education Shape
    op.alter_column(
        "groups",
        "education_shape",
        existing_type=postgresql.ENUM(
            "KUNDUZGI", "KECHKI", "SIRTQI", "MASOFAVIY", name="educationshape"
        ),
        type_=sa.String(),
        existing_nullable=False,
        postgresql_using="education_shape::text",
    )

    # Convert 'KUNDUZGI' -> 'kunduzgi', etc.
    op.execute("UPDATE groups SET education_shape = lower(education_shape)")
    op.execute("DROP TYPE educationshape")

    # 2. Workloads: Load Type
    op.alter_column(
        "workloads",
        "load_type",
        existing_type=postgresql.ENUM(
            "LECTURE", "PRACTICE", "LAB", "SEMINAR", name="loadtype"
        ),
        type_=sa.String(),
        existing_nullable=False,
        postgresql_using="load_type::text",
    )

    # Convert 'LECTURE' -> 'lecture', etc.
    op.execute("UPDATE workloads SET load_type = lower(load_type)")
    op.execute("DROP TYPE loadtype")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate types
    op.execute("CREATE TYPE loadtype AS ENUM ('LECTURE', 'PRACTICE', 'LAB', 'SEMINAR')")
    op.execute(
        "CREATE TYPE educationshape AS ENUM ('KUNDUZGI', 'KECHKI', 'SIRTQI', 'MASOFAVIY')"
    )

    # Revert data (lower -> UPPER)
    op.execute("UPDATE workloads SET load_type = upper(load_type)")
    op.execute("UPDATE groups SET education_shape = upper(education_shape)")

    op.alter_column(
        "workloads",
        "load_type",
        existing_type=sa.String(),
        type_=postgresql.ENUM("LECTURE", "PRACTICE", "LAB", "SEMINAR", name="loadtype"),
        existing_nullable=False,
        postgresql_using="load_type::loadtype",
    )
    op.alter_column(
        "groups",
        "education_shape",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "KUNDUZGI", "KECHKI", "SIRTQI", "MASOFAVIY", name="educationshape"
        ),
        existing_nullable=False,
        postgresql_using="education_shape::educationshape",
    )
    # ### end Alembic commands ###
