"""Add_group_fields

Revision ID: e5a956f2ff19
Revises: 6d4baf5dd6f0
Create Date: 2026-01-13 17:40:53.596848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a956f2ff19'
down_revision: Union[str, Sequence[str], None] = '6d4baf5dd6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('student_count', sa.Integer(), nullable=False))
    
    # Create enum type manually
    education_shape_enum = sa.Enum('KUNDUZGI', 'KECHKI', 'SIRTQI', 'MASOFAVIY', name='educationshape')
    education_shape_enum.create(op.get_bind())
    
    op.add_column('groups', sa.Column('education_shape', education_shape_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'education_shape')
    op.drop_column('groups', 'student_count')
    
    # Drop enum type manually
    education_shape_enum = sa.Enum('KUNDUZGI', 'KECHKI', 'SIRTQI', 'MASOFAVIY', name='educationshape')
    education_shape_enum.drop(op.get_bind())
    # ### end Alembic commands ###
