"""add_seminar_to_load_type

Revision ID: f59a51bc0bbc
Revises: 4cc0c1bf1b08
Create Date: 2026-01-14 09:11:02.960043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f59a51bc0bbc'
down_revision: Union[str, Sequence[str], None] = '4cc0c1bf1b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
