"""recreate_subgroup_migration

Revision ID: fc9c11fde0eb
Revises: e43bc532666b
Create Date: 2026-01-21 10:15:03.658084

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc9c11fde0eb"
down_revision: Union[str, Sequence[str], None] = "e43bc532666b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subgroups_id"), table_name="subgroups")
    op.drop_table("subgroups")
    op.add_column(
        "groups",
        sa.Column(
            "has_lab_subgroups",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.drop_column("groups", "he_lab_split")
    op.drop_column("workloads", "subgroup_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workloads",
        sa.Column("subgroup_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "groups",
        sa.Column(
            "he_lab_split",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("groups", "has_lab_subgroups")
    op.create_table(
        "subgroups",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("student_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("subgroups_group_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("subgroups_pkey")),
    )
    op.create_index(op.f("ix_subgroups_id"), "subgroups", ["id"], unique=False)
    # ### end Alembic commands ###
